default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: dev
  username: root
  password: roland57

test:
  <<: *default
  database: test
  username: root
  password: roland57
production:
  <<: *default
  database: prod
  username: root
  password:
